### ISSUE TITLE
Packages outdated

### ISSUE THREAD

**Issue by martijn00** [akavache/Akavache#187]
I get errors on initializing Akavache because the packages Splat and SQLitePCL.raw that are used in Akavache are older then the latest that are automatically downloaded from Nuget.

After i installed the older versions of the packages i got this error:

```
Failed to initialize Akavache properly. Do you have a reference to Akavache.dll?
   at Akavache.Sqlite3.Registrations.Register(IMutableDependencyResolver resolver)
   at Akavache.DependencyResolverMixin.InitializeAkavache(IMutableDependencyResolver This)
   at Akavache.BlobCache.<.cctor>b__0()
   at Splat.Locator.RegisterResolverCallbackChanged(Action callback)
   at Akavache.BlobCache..cctor()
```

Could you update the dependencies and publish an update to Akavache? 
Do you have a clue about the error?

**Comment by paulcbetts** [comment]
Can you try this with the latest version (4.1.0)?

**Comment by martijn00** [comment]
Sure, i'll give it a try tomorrow.

**Comment by martijn00** [comment]
I've updated the packages and everything seems to work. Thanks for your work!
