### ISSUE TITLE
Akavache not working on Windows phone 8.1.

### ISSUE THREAD

**Issue by bibhusundarparida** [akavache/Akavache#239]
Akavache not working on Windows 8.1. It gives an error mentioning. SQLite3 could not be loaded.Here is the details----

Inner Exception---
      Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Error message-  
       The type initializer for 'SQLitePCL.raw' threw an exception.

Stack Trace-  
         at SQLitePCL.raw.sqlite3_open_v2(String filename, sqlite3& db, Int32 flags, String vfs)
   at Akavache.Sqlite3.Internal.SQLite3.Open(String filename, sqlite3& db, Int32 flags, IntPtr zVfs)
   at Akavache.Sqlite3.Internal.SQLiteConnection..ctor(String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks)
   at Akavache.Sqlite3.Internal.SQLiteConnection..ctor(String databasePath, Boolean storeDateTimeAsTicks)
   at Akavache.Sqlite3.SQLitePersistentBlobCache..ctor(String databaseFile, IScheduler scheduler)
   at Akavache.Sqlite3.Registrations.<>c__DisplayClass6.<Register>b__0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.get_Value()
   at Akavache.Sqlite3.Registrations.<>c__DisplayClass6.<Register>b__1()
   at Splat.ModernDependencyResolver.GetService(Type serviceType, String contract)
   at Splat.DependencyResolverMixins.GetService[T](IDependencyResolver This, String contract)
   at Akavache.BlobCache.get_LocalMachine()
   at Demotest.CurrentBalance.checkBalance()
   at Demotest.CurrentBalance..ctor()
   at Demotest.Demotest_XamlTypeInfo.XamlTypeInfoProvider.Activate_7_CurrentBalance()
   at Demotest.Demotest_XamlTypeInfo.XamlUserType.ActivateInstance()

**Comment by martingemme** [comment]
Versions of:
Splat ?
SQLitePCL.raw ?
Akavache ?
Akavache.Sqlite3 ?

**Comment by thomasvdb** [comment]
I'm having the same issue.
I marked my application as x86 and added the C++ runtime.

Versions:
Splat --> 1.6.0.0
SQLitePCL.raw --> 0.8.2.0
Akavache --> 4.1.1.0
Akavache.Sqlite3 --> 4.1.1.0

If you need more info, let me know.

**Comment by thomasvdb** [comment]
I've added the precompiled binary for Windows Phone 8 to my project to solve this error.
You can find it on the download page of SQLite: https://www.sqlite.org/download.html

**Comment by Janniesouta** [comment]
and not running during creator
 MacHen
C++
