### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by sanchitanand** [akavache/Akavache#309]
heres a portion of my code    

``````
       ```
``````

try
            {
                verify = await BlobCache.UserAccount.GetObject<UserModel>(user.username);
            }

```
        catch(KeyNotFoundException a)
        {
            verify = user;
           await BlobCache.UserAccount.InsertObject<UserModel>(user.username, user);

        }
        catch(Exception e)
        {
            System.Diagnostics.Debug.WriteLine(String.Format("Exception here!:{0}", e.GetType()));
            System.Diagnostics.Debug.WriteLine(String.Format("Exception here!:{0}", e.Message));
            System.Diagnostics.Debug.WriteLine(String.Format("Exception here!:{0}",e.StackTrace));
        }
```

```

I get this exception


Exception here!:System.ArgumentNullException
 Exception here!:Value cannot be null.
Parameter name: source
 Exception here!:  at System.Reactive.Linq.Observable.SelectMany[TSource,TResult] (IObservable1 source, System.Func2 selector) [0x00003] in <filename unknown>:0 
  at Akavache.JsonSerializationMixin.GetObject[T] (IBlobCache This, System.String key) [0x00037] in <filename unknown>:0 
  at App8.LoginActivity+<loginButtonClick>d__6.MoveNext () [0x0008b] in C:\Users\LoginActivity.cs:50 
```

**Comment by flagbug** [comment]
Please provide a fully reproducible sample

**Comment by mvanbeusekom** [comment]
I have get a similar exception on Android. It happens when I navigate back (from an activity displaying detailed information, to the overview activity) using the back button of the device. 

I noticed that the actual the object returned from `BlobCache.LocalMachine` changes from `Akavache.Sqlite3.SQLitePersistentBlobCache` (this is good, all works fine) to `Akavache.BlobCache.ShutdownBlobCache` (this is where it crashes). So here is the process:

1. First I get to my overview activity and call the function below. Calling `BlobCache.LocalMachine` returns an instance of `Akavache.Sqlite3.SQLitePersistentBlobCache`;
2. I navigate away from the overview activity to the detail activity;
3. I use the Android device 'Back' button to navigate back to the overview activity. The function below is called again, however this time the `BlobCache.LocalMachine` returns an instance of `Akavache.BlobCache.ShutdownBlodCache`. Calling the `GetAndFetchObject<>` method on this instance results in the `System.ArgumentNullException`.

Here is the function I am using:

```
public async Task<IEnumerable<Shift>> GetShiftsForMonthAsync(int employeeId, int month, int year)
{
    IEnumerable<Shift> shifts;

    var promise = BlobCache.LocalMachine.GetAndFetchLatest(
                $"ShiftsFor_{month}-{year}",
                async () => await _shiftService.GetShiftsForMonthAsync(employeeId, month, year).ConfigureAwait(false),
                null,
                null);

    promise.Subscribe(s => shifts = s);

    shifts = await promise.FirstOrDefaultAsync();
    return shifts;
}
```

Here is my stack trace:

```
Xamarin caused by: android.runtime.JavaProxyThrowable: System.ArgumentNullException: Value cannot be null.
Parameter name: source
  at System.Reactive.Linq.Observable.SelectMany[TSource,TResult] (IObservable`1 source, System.Func`2 selector) <0xdc810e38 + 0x000ac> in <filename unknown>:0 
  at Akavache.JsonSerializationMixin.GetObject[T] (IBlobCache This, System.String key) <0xdb330320 + 0x0017f> in <filename unknown>:0 
  at Akavache.JsonSerializationMixin.GetAndFetchLatest[T] (IBlobCache This, System.String key, System.Func`1 fetchFunc, System.Func`2 fetchPredicate, Nullable`1 absoluteExpiration, Boolean shouldInvalidateOnError) <0xdc8a8af8 + 0x00397> in <filename unknown>:0 
  at Akavache.JsonSerializationMixin.GetAndFetchLatest[T] (IBlobCache This, System.String key, System.Func`1 fetchFunc, System.Func`2 fetchPredicate, Nullable`1 absoluteExpiration) <0xdc8a8868 + 0x0010b> in <filename unknown>:0 
  at Uurwerk.DataStore.Akavache.ShiftStore+<GetShiftsForMonthAsync>c__async0.MoveNext () <0xdc8a7b30 + 0x00357> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0xdb2f08f8 + 0x00024> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0xdc9ead30 + 0x000c3> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0xdc9eac50 + 0x0008b> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0xdc8604f0 + 0x0003f> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0xdc860430 + 0x0001b> in <filename unknown>:0 
  at Uurwerk.DataStore.Akavache.ShiftStore+<GetShiftsForDateAsync>c__async1.MoveNext () <0xdc8b7690 + 0x0022b> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0xdb2f08f8 + 0x00024> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0xdc9ead30 + 0x000c3> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0xdc9eac50 + 0x0008b> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0xdc8604f0 + 0x0003f> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0xdc860430 + 0x0001b> in <filename unknown>:0 
  at Uurwerk.Core.ViewModels.CalendarViewModel+<LoadShiftsForSelectedDate>c__async3+<LoadShiftsForSelectedDate>c__AnonStorey6+<LoadShiftsForSelectedDate>c__async5.MoveNext () <0xdc8b6d88 + 0x0017f> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0xdb2f08f8 + 0x00024> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0xdc9ead30 + 0x000c3> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0xdc9eac50 + 0x0008b> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0xdc8604f0 + 0x0003f> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0xdc890808 + 0x00017> in <filename unknown>:0 
  at Route2IT.Mobile.Core.ViewModels.BaseViewModel+<LongRunningTaskAsync>c__async0.MoveNext () <0xdb1c57e8 + 0x0017b> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0xdb2f08f8 + 0x00024> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0xdc9ead30 + 0x000c3> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0xdc9eac50 + 0x0008b> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0xdc8604f0 + 0x0003f> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0xdc890808 + 0x00017> in <filename unknown>:0 
  at Uurwerk.Core.ViewModels.CalendarViewModel+<LoadShiftsForSelectedDate>c__async3.MoveNext () <0xdc8b6368 + 0x002a7> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0xdb2f08f8 + 0x00024> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0xdc9ead30 + 0x000c3> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0xdc9eac50 + 0x0008b> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0xdc8604f0 + 0x0003f> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0xdc890808 + 0x00017> in <filename unknown>:0 
  at Uurwerk.Core.ViewModels.CalendarViewModel+<OnPropertyChanged>c__async0.MoveNext () <0xdc8a68f0 + 0x0025b> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0xdb2f08f8 + 0x00024> in <filename unknown>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) <0xdc9eb8c0 + 0x00047> in <filename unknown>:0 
  at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () <0xdc81b0a0 + 0x00027> in <filename unknown>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () <0xdc81aec0 + 0x0003f> in <filename unknown>:0 
  at Java.Lang.IRunnableInvoker.n_Run (IntPtr jnienv, IntPtr native__this) <0xdc81adf0 + 0x0004f> in <filename unknown>:0 
  at (wrapper dynamic-method) System.Object:2121b381-a327-46dd-965e-5d858df26fdd (intptr,intptr)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:168)
	at android.app.ActivityThread.main(ActivityThread.java:5845)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
```

**Comment by flagbug** [comment]
Again, please provide a fully reproducible sample, otherwise I can't debug this

**Comment by mvanbeusekom** [comment]
coming up (just figured I will give some more detailed information)

**Comment by mvanbeusekom** [comment]
I feel so stupid and my apologies for wasting your time. I found the bug. 

My coworker moved the `BlobCache.Shutdown().Wait()` method call from `OnDestroy` method in the main activity to a base activity class. Meaning when any activity is destroyed it will shutdown Akavache.

So please ignore my bug report.
